window.TOOTOO_CONFIG = {
  owner: 'theo-armour',
  repo: '2026',
  appName: '2026',
  storagePrefix: 'ta-2026',
  sourceRepoUrl: 'https://github.com/theo-armour/2026',
  themeColor: '#2874a6',
  subtitle: '',
  faviconLetters: '26',
  faviconColor: '#2874a6',
  subtitle: 'a GitHub repository browser',
  headingFontUrl: 'https://fonts.googleapis.com/css2?family=Patua+One&display=swap',
  headingFont: '"Patua One", serif',
  hiddenFiles: [ 'tootoo.config.js' ],
  hiddenFolders: [ 'Images' ],
};
